# Generated by Django 5.0 on 2023-12-08 21:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uu_id', models.UUIDField(default=uuid.uuid4)),
                ('title', models.CharField(max_length=20)),
                ('description', models.TextField(max_length=200)),
                ('genre', models.CharField(choices=[('action', 'action'), ('comedy', 'comedy'), ('horror', 'horror')], max_length=100)),
            ],
        ),
    ]
