# Generated by Django 5.0 on 2023-12-09 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='uu_id',
            new_name='uuid',
        ),
        migrations.AddField(
            model_name='movie',
            name='cover_image',
            field=models.ImageField(help_text='Cover Image', null=True, upload_to='\\media\\movie_images'),
        ),
    ]
