# Generated by Django 5.0 on 2023-12-09 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_uu_id_movie_uuid_movie_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='cover_image',
            field=models.ImageField(help_text='Cover Image', null=True, upload_to='media\\movie_images'),
        ),
    ]
