# Generated by Django 5.0 on 2023-12-09 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_movie_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='cover_image',
            field=models.ImageField(help_text='Cover Image', null=True, upload_to='movie_images'),
        ),
    ]
