# Generated by Django 5.0 on 2023-12-09 17:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_genre_remove_movie_genre_movie_genres_serie'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AddField(
            model_name='movie',
            name='duration_min',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='serie',
            name='duration_min',
            field=models.IntegerField(null=True),
        ),
    ]
