# Generated by Django 5.0 on 2023-12-16 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_movie_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='serie',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
