# Generated by Django 5.0 on 2023-12-17 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_rename_list_listcontent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listcontent',
            name='movie',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='core.movie'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='listcontent',
            name='serie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.serie'),
        ),
    ]
