# Generated by Django 5.0 on 2023-12-17 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_moviecontent_list_content_seriecontent_list_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviecontent',
            name='content_type',
            field=models.CharField(default='movie', max_length=255),
        ),
        migrations.AddField(
            model_name='seriecontent',
            name='content_type',
            field=models.CharField(default='serie', max_length=255),
        ),
    ]
