# Generated by Django 5.0 on 2023-12-17 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_remove_listcontent_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='name',
        ),
        migrations.RemoveField(
            model_name='moviecontent',
            name='list_content',
        ),
        migrations.RemoveField(
            model_name='seriecontent',
            name='list_content',
        ),
        migrations.AddField(
            model_name='content',
            name='list_content',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.listcontent'),
        ),
    ]
