# Generated by Django 5.0 on 2023-12-17 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_remove_content_name_remove_moviecontent_list_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='list_content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.listcontent'),
        ),
    ]
