# Generated by Django 5.0 on 2023-12-17 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_content_list_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='list_content',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.listcontent'),
        ),
    ]
