# Generated by Django 5.0 on 2023-12-30 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_chapter_season'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='season',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.season'),
            preserve_default=False,
        ),
    ]
