# Generated by Django 5.0 on 2023-12-30 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_chapter_season'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serie',
            name='duration_min',
        ),
    ]
