# Generated by Django 5.0 on 2024-01-03 20:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_remove_serie_duration_min'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
