# Generated by Django 5.0 on 2024-01-21 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_alter_movie_genres_alter_movie_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serie',
            name='genres',
            field=models.ManyToManyField(blank=True, to='core.genre'),
        ),
    ]
