# Generated by Django 5.0 on 2024-01-21 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_alter_serie_genres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serie',
            name='cover_image',
            field=models.ImageField(help_text='Cover Image', null=True, upload_to='serie_images'),
        ),
    ]
