# Generated by Django 5.0 on 2024-01-28 11:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_alter_movie_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='video',
            field=models.FileField(blank=True, upload_to='serie_videos', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm', 'mkv'])]),
        ),
    ]
